### ISSUE TITLE
Cannot convert mdj file to openapi specs

### ISSUE THREAD

**Issue by asyrofist** [edi3/edi3-uml-profile#15]
please help me, I can't  export any  file (yaml or json) from this open api converter. I have used this file mdj any way..
https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj

please, fix it soon..

**Comment by mrtnmrtn** [comment]
@asyrofist - What version of the OpenAPI3.0 Generator are you using? What steps are you performing? 

I can generate an OpenAPI spec from the file you linked (with some error messages).  

I installed the latest version (0.7.1-rc2) by choosing 'Install From Url...' in the StarUML extension manager and entering https://github.com/gs-gs/staruml-cefact as the address.

Once the extension is installed and the SampleModel.mdj file is open:
- select Tools->OpenAPI->Generate Specs
- select the UNCEFACT/TransportDomain/Movements/Movements diagram and then OK
- choose the output file type and OK
- select your target folder then Save
You may get a couple of alerts/error messages, close them to continue.

**Comment by asyrofist** [comment]
Thank you, I'll try soon.. 👍
